---
title: "Fake data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(broom)
library(purrr)
library(tidyr)
library(rstan)

find_seeds <- function(seed){
  set.seed(seed)
  N  <- 100
  fake_data <- tibble(x = rnorm(n = N, mean = 0, sd = 1),
                t = rbinom(n = N, size = 1, prob = 0.5),
                e = rnorm(n = N, mean = 0, sd = 0.4),
                seed = seed) %>% 
    mutate(y = 0.6*x + e)
  
  lm1 <- fake_data %>% 
    lm(data = ., formula = y ~ x + t) %>% 
    tidy(.) %>% 
    filter(term=="t") %>% 
    select(-term) %>% 
    mutate(plt0.05 = case_when(p.value < 0.05 ~ 1,
                               TRUE ~ 0),
           seed = seed)
  
  out <- inner_join(fake_data, lm1, by="seed") %>% 
    group_by(estimate, std.error, statistic, p.value, seed, plt0.05) %>% 
    nest() 
  return(out)
}

seeds <- 1:1000

good_seeds <- map_df(.x = seeds, .f = ~find_seeds(seed = .x)) %>% 
  filter(plt0.05 ==1) %>% 
  arrange(-estimate) %>% 
  mutate(idx = 1:n())
```


```{r}
seed <- 1981
set.seed(seed)
N  <- 100

fake_data <- tibble(
  x = rnorm(n = N, mean = 0, sd = 1),
  t = rbinom(n = N, size = 1, prob = 0.5),
  e = rnorm(n = N, mean = 0, sd = 0.4),
  seed = seed
  ) %>% 
  mutate(y = 0.6*x + 0.02 *t + e)
```


```{r}

lm1 <- fake_data %>% 
    lm(data = ., formula = y ~ x + t) %>% 
    tidy(.) %>% 
    filter(term=="t") %>% 
    select(-term) %>% 
    mutate(plt0.05 = case_when(p.value < 0.05 ~ 1,
                               TRUE ~ 0),
           seed = seed)

lm1
```

```{r}
lm1 <- lm(data = fake_data, formula = y ~ x + t) %>% 
  tidy(., conf.int=T, conf.level=0.95) %>% 
  filter(term=="t") 


ggplot(data = lm1, aes(y=estimate, x= term)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) +
  geom_hline(yintercept = 0.01) + 
  scale_y_continuous(breaks = seq(-0.2, 0.2, by = 0.02)) +
  theme_bw() +
  xlab("") + 
  ylab("Treatment Effect") + 
  theme(
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank())

```


```{stan output.var='model1'}
data{
  int N;
  vector[N] y;
  vector[N] x;
  vector[N] t;
}

parameters{
  real alpha;
  real beta;
  real tau;
  real<lower=0> sigma;
}

model{
  alpha ~ std_normal();
  beta ~ std_normal();
  tau ~ normal(0.01, 0.05); // std_normal();
  sigma ~ std_normal();
  y ~ normal(alpha + beta * x + tau * t, sigma);
}

```

```{r}
stan_data <- list(N = nrow(fake_data),
                  y= fake_data$y,
                  x = fake_data$x,
                  t = fake_data$t)

fit1 <- sampling(model1, data = stan_data, seed=1982)

tau <- as.data.frame(fit1, pars='tau') 

b1 <- vizdraws::vizdraws(prior = "N(0.01, 0.05)", 
                         posterior = tau$tau, 
                         MME = 0.01, xlim = c(-0.5,0.5), 
                         display_mode_name = TRUE)

b1
```

```{r}
seed <- 9782
set.seed(seed)
N  <- 200

fake_data <- tibble(
  x = rnorm(n = N, mean = 0, sd = 1),
  t = rbinom(n = N, size = 1, prob = 0.5),
  e = rnorm(n = N, mean = 0, sd = 0.4),
  seed = seed
  ) %>% 
  mutate(y = 0.6*x + 0.02 *t + e)

stan_data <- list(N = nrow(fake_data),
                  y= fake_data$y,
                  x = fake_data$x,
                  t = fake_data$t)

fit1 <- sampling(model1, data = stan_data, seed=1982)

tau <- as.data.frame(fit1, pars='tau') 
```

```{r}
lm1 <- lm(data = fake_data, formula = y ~ x + t) %>% 
  tidy(., conf.int=T, conf.level=0.95) %>% 
  filter(term=="t") 


ggplot(data = lm1, aes(y=estimate, x= term)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high)) +
  theme_bw() +
  xlab("") + 
  ylab("Treatment Effect") + 
  theme(
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank())
```



